name: build 
on: 
  push:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'docker-image to scan'     
        default: 'rust:1.46.0'
      output_file:
        description: 'output file'     
        default: 'rust.spdx'
      output_type:
        description: 'output type'     
        default: 'spdxtagvalue'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@jamiemagee
        id: scan
        with:
          image: ${{ github.event.inputs.docker_image }}
          format: ${{ github.event.inputs.output_type }}
          output: ${{ github.event.inputs.output_file }}
      - uses: actions/upload-artifact@v2
        with:
          name: tern 
          path: ${{ steps.scan.outputs.file }} 
