name: build 
on: 
  push:
  workflow_dispatch:
    inputs:
      docker-image:
        description: 'docker-image to scan'     
        default: 'rust:1.46.0'
      output-file:
        description: 'output file'     
        default: 'rust.spdx'
      output-type:
        description: 'output type'     
        default: 'spdxtagvalue'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@jamiemagee
        id: scan
        with:
          image: rust:1.46.0 
          format: spdxtagvalue
          output: rust.spdx
      - uses: actions/upload-artifact@v2
        with:
          name: tern 
          path: ${{ steps.scan.outputs.file }} 
