name: build 
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/tern-action@add-scancode
        id: scan
        with:
          image: rust:1.46.0 
          format: spdx
          output: rust.spdx
      - uses: actions/upload-artifact@v2
        with:
          name: tern 
          path: ${{ steps.scan.outputs.file }} 
